### ISSUE TITLE
possible issue with split_folders_files.m

### ISSUE THREAD

**Issue by JeffFessler** [mechatoz/convolt#1]
A user reported by email:
`split_folders_files.m` line 38: it should be
`dirs = cell2mat(B(5,:))`
instead of
`dirs = cell2mat(B(4,:))`
as the function was loading the sub-directories instead of the image files.
"Perhaps that depends on the Matlab version (I am using Matlab 2020a)"

**Comment by mechatoz** [comment]
yes, this depends on the Matlab version. for Matlab ver. less than 2016a, i suggest using dirs = cell2mat(B(4,:)) instead of dirs = cell2mat(B(5,:)). (i tested it on Matlab 2015b and '4' works.)
