### ISSUE TITLE
problem in BPEGM_CAOL_2D_TF.m, padding function

### ISSUE THREAD

**Issue by abousse** [mechatoz/convolt#5]
in `PadFuncPadFunc`

`bpad = padarray(b, [psf_radius, psf_radius, 0], 'circular', 'both'); ` should be  `bpad = padarray(b, [psf_radius(1), psf_radius(2), 0], 'circular', 'both');`

**Comment by JeffFessler** [comment]
thanks for all these refinements.  for now i am leaving it to il yong to "accept" them because this is his repo.

**Comment by mechatoz** [comment]
this refinement is approved and merged. thanks again for the requirement!
